networks:
  markdowner-network:
    name: markdowner-network
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    networks:
      markdowner-network:
        ipv4_address: 10.0.0.10
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    networks:
      markdowner-network:
        ipv4_address: 10.0.0.15
    ports:
      - 15432:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    restart: unless-stopped

  redis:
    image: redis:latest
    container_name: redis
    networks:
      markdowner-network:
        ipv4_address: 10.0.0.20
    ports:
      - 6379:6379
    command: >
      redis-server
      --requirepass "${REDIS_PASSWORD}"
      --maxmemory ${REDIS_MAX_MEMORY}
      --maxmemory-policy allkeys-lru
      --save ""
      --appendonly no
    restart: unless-stopped

  springboot:
    image: openjdk:21-jdk
    container_name: springboot
    networks:
      markdowner-network:
        ipv4_address: 10.0.0.25
    ports:
      - 8080:8080
    environment:
      SPRINGBOOT_DATASOURCE_USERNAME: ${POSTGRES_USER}
      SPRINGBOOT_DATASOURCE_PASSWORD: ${POSTGRES_PASSWORD}
      SPRINGBOOT_DATASOURCE_URL: jdbc:postgresql://10.0.0.10:5432/${POSTGRES_DB}
      SPRINGBOOT_JPA_HIBERNATE_DDL_AUTO: ${SPRINGBOOT_JPA_HIBERNATE_DDL_AUTO}
      SPRINGBOOT_DATA_REDIS_HOST: 10.0.0.20
      SPRINGBOOT_DATA_REDIS_PORT: 6379
      SPRINGBOOT_DATA_REDIS_PASSWORD: ${SPRINGBOOT_DATA_REDIS_PASSWORD}
      SPRINGBOOT_CACHE_REDIS_TIME_TO_LIVE: ${SPRINGBOOT_CACHE_REDIS_TIME_TO_LIVE}
    volumes:
      - ./:/app
    working_dir: /app
    stdin_open: true
    tty: true
    restart: unless-stopped
