server:
  port: 8080
spring:
  application:
    name: api
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      encoding: UTF-8
  datasource:
    username: ${SPRINGBOOT_DATASOURCE_USERNAME}
    password: ${SPRINGBOOT_DATASOURCE_PASSWORD}
    url: ${SPRINGBOOT_DATASOURCE_URL}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        hbm2ddl:
          '[import_files]': migration.sql,settlement.sql
    hibernate:
      ddl-auto: ${SPRINGBOOT_JPA_HIBERNATE_DDL_AUTO}
  data:
      redis:
        host: ${SPRINGBOOT_DATA_REDIS_HOST}
        port: ${SPRINGBOOT_DATA_REDIS_PORT}
        password: ${SPRINGBOOT_DATA_REDIS_PASSWORD}
        timeout: 60000
        connect-timeout: 10000
        lettuce:
          pool:
            max-active: 8
            max-idle: 8
            min-idle: 2
            max-wait: -1ms
          shutdown-timeout: 100ms
  cache:
    type: redis
    redis:
      time-to-live: ${SPRINGBOOT_CACHE_REDIS_TIME_TO_LIVE}
      key-prefix: "markdowner_api:"
      use-key-prefix: true
